{
 "title": "Redpanda Starter (Prometheus)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Broker Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"redpanda\"})"
    }
   ]
  },
  {
   "title": "Scrape Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds{job=\"redpanda\"})"
    }
   ]
  },
  {
   "title": "Produce Rate by Topic (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(vectorized_cluster_partition_batches_produced{namespace=\"kafka\"}[5m]))"
    }
   ]
  }
 ]
}