global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml
  - /etc/prometheus/rules-slo.yml

scrape_configs:
  - job_name: redpanda
    metrics_path: /metrics
    static_configs:
      - targets: ["redpanda:9644"]
    # optional relabels here if you want to add env/cluster labels

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]
  
  - job_name: kafka_exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: node_exporter
    static_configs:
      - targets: ["node-exporter:9100"]