route:
  group_by: ["alertname", "service"]
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h
  receiver: dev-null
  routes:
    - matchers:
        - severity="critical"
      receiver: dev-null   # replace with slack or email below
    - matchers:
        - severity="warning"
      receiver: dev-null

receivers:
  - name: dev-null

  # --- Example: Slack (uncomment + set your webhook) ---
  # - name: slack-alerts
  #   slack_configs:
  #     - api_url: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
  #       channel: "#alerts"
  #       send_resolved: true
  #       title: "[{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}"
  #       text: "{{ range .Alerts }}• {{ .Annotations.description }} ({{ .Labels.severity }}){{ \"\\n\" }}{{ end }}"

  # --- Example: Email (SMTP must be configured in Alertmanager env) ---
  # - name: email-alerts
  #   email_configs:
  #     - to: "oncall@example.com"
  #       send_resolved: true