name: Agent Worker
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch: {}

jobs:
  work:
    runs-on: ubuntu-latest
    env:
      RP_BOOTSTRAP: 'd2heugc8ljef72usu9gg.any.ap-south-1.mpx.prd.cloud.redpanda.com:9092'
      RP_USERNAME:  'aman'
      RP_PASSWORD:  'jJOSBV0ng8qgpfg8NOMlk4iS7EIbEv'
      TOPIC_INTENTS: 'agent-intents'
      TOPIC_OUTPUTS: 'agent-outputs'
      GROUP_ID:      'agent-worker'
      POLL_SECONDS:  '20'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install kafka-python
      - name: Consume intents and publish results
        run: |
          python agent/worker.py | tee /tmp/worker.json
          echo "## Worker Output" >> $GITHUB_STEP_SUMMARY
          cat /tmp/worker.json >> $GITHUB_STEP_SUMMARY
